/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

/**
 *
 * @author Radenixlol
 */
public class InterfazSimulation extends javax.swing.JFrame {

    Admin admin = new Admin(this);

    /**
     * Creates new form InterfazSimulation
     */
    public InterfazSimulation() {
        initComponents();
        admin.init();
    }

    public void UpdateCola(Boolean z, int type, Cola cola) {
        String text = "";
        boolean empty = cola.ColaVacia();
        if (z) {
            if (!empty) {
                Personajes place = cola.getFinCola();
                text += place.getId();
                place = place.getAnterior();
                while (place != null) {
                    text += " -- ";
                    text += place.getId();
                    place = place.getAnterior();
                }
            }
            switch (type) {
                case 1 -> {
                    Cola1Z.setText(text);
                }
                case 2 -> {
                    Cola2Z.setText(text);
                }
                case 3 -> {
                    Cola3Z.setText(text);
                }
                case 4 -> {
                    ColaRZ.setText(text);
                }
            }
        } else {
            if (!empty) {
                Personajes place = cola.getInicioCola();
                text += place.getId();
                place = place.getSiguiente();
                while (place != null) {
                    text += " -- ";
                    text += place.getId();
                    place = place.getSiguiente();
                }
            }
            switch (type) {
                case 1 -> {
                    Cola1SF.setText(text);
                }
                case 2 -> {
                    Cola2SF.setText(text);
                }
                case 3 -> {
                    Cola3SF.setText(text);
                }
                case 4 -> {
                    ColaRSF.setText(text);
                }
            }
        }
    }

    public void UpdateTextZ() {
        String nameZ = admin.getSimulador().getZ().getNombre();
        CasillaZ.setText(nameZ);
        
    }
    
    public void UpdateTextSF() {
        String nameSF = admin.getSimulador().getSF().getNombre();
        CasillaSF.setText(nameSF);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Scroll1Z = new javax.swing.JScrollPane();
        Cola1Z = new javax.swing.JTextArea();
        Scroll2Z = new javax.swing.JScrollPane();
        Cola2Z = new javax.swing.JTextArea();
        Scroll3Z3 = new javax.swing.JScrollPane();
        Cola3Z = new javax.swing.JTextArea();
        ScrollRZ = new javax.swing.JScrollPane();
        ColaRZ = new javax.swing.JTextArea();
        Scroll1SF = new javax.swing.JScrollPane();
        Cola1SF = new javax.swing.JTextArea();
        Scroll2SF = new javax.swing.JScrollPane();
        Cola2SF = new javax.swing.JTextArea();
        Scroll3SF = new javax.swing.JScrollPane();
        Cola3SF = new javax.swing.JTextArea();
        ScrollRSF = new javax.swing.JScrollPane();
        ColaRSF = new javax.swing.JTextArea();
        CasillaZ = new javax.swing.JLabel();
        StatusZ = new javax.swing.JTextField();
        StatusSF = new javax.swing.JTextField();
        CasillaSF = new javax.swing.JLabel();
        CountZ = new javax.swing.JTextField();
        CountSF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Scroll1Z.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Scroll1Z.setFocusable(false);

        Cola1Z.setEditable(false);
        Cola1Z.setColumns(20);
        Cola1Z.setRows(5);
        Scroll1Z.setViewportView(Cola1Z);

        Scroll2Z.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Scroll2Z.setFocusable(false);

        Cola2Z.setEditable(false);
        Cola2Z.setColumns(20);
        Cola2Z.setRows(5);
        Scroll2Z.setViewportView(Cola2Z);

        Scroll3Z3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Scroll3Z3.setFocusable(false);

        Cola3Z.setEditable(false);
        Cola3Z.setColumns(20);
        Cola3Z.setRows(5);
        Scroll3Z3.setViewportView(Cola3Z);

        ScrollRZ.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrollRZ.setFocusable(false);

        ColaRZ.setEditable(false);
        ColaRZ.setColumns(20);
        ColaRZ.setRows(5);
        ScrollRZ.setViewportView(ColaRZ);

        Scroll1SF.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Scroll1SF.setFocusable(false);

        Cola1SF.setEditable(false);
        Cola1SF.setColumns(20);
        Cola1SF.setRows(5);
        Scroll1SF.setViewportView(Cola1SF);

        Scroll2SF.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Scroll2SF.setFocusable(false);

        Cola2SF.setEditable(false);
        Cola2SF.setColumns(20);
        Cola2SF.setRows(5);
        Scroll2SF.setViewportView(Cola2SF);

        Scroll3SF.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Scroll3SF.setFocusable(false);

        Cola3SF.setEditable(false);
        Cola3SF.setColumns(20);
        Cola3SF.setRows(5);
        Scroll3SF.setViewportView(Cola3SF);

        ScrollRSF.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrollRSF.setFocusable(false);

        ColaRSF.setEditable(false);
        ColaRSF.setColumns(20);
        ColaRSF.setRows(5);
        ScrollRSF.setViewportView(ColaRSF);

        CasillaZ.setBackground(new java.awt.Color(0, 110, 168));
        CasillaZ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CasillaZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        StatusZ.setEditable(false);
        StatusZ.setBackground(new java.awt.Color(0, 153, 0));
        StatusZ.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StatusZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusZ.setText("WIN");
        StatusZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusZActionPerformed(evt);
            }
        });

        StatusSF.setEditable(false);
        StatusSF.setBackground(new java.awt.Color(255, 0, 0));
        StatusSF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StatusSF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusSF.setText("LOSE");

        CasillaSF.setBackground(new java.awt.Color(51, 204, 255));
        CasillaSF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CasillaSF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CountZ.setEditable(false);
        CountZ.setBackground(new java.awt.Color(204, 204, 204));
        CountZ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CountZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CountZ.setText("0");
        CountZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountZActionPerformed(evt);
            }
        });

        CountSF.setEditable(false);
        CountSF.setBackground(new java.awt.Color(204, 204, 204));
        CountSF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CountSF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CountSF.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollRSF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ScrollRZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Scroll3Z3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Scroll2Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Scroll1Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StatusZ, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CasillaZ, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CasillaSF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatusSF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(CountZ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CountSF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(Scroll1SF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Scroll2SF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Scroll3SF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Scroll1SF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Scroll2SF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Scroll3SF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(ScrollRSF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CountSF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CasillaSF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CasillaZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(CountZ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusSF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusZ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Scroll1Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Scroll2Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scroll3Z3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ScrollRZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StatusSF.getAccessibleContext().setAccessibleName("");
        StatusSF.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CountZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountZActionPerformed

    private void StatusZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusZActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfazSimulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CasillaSF;
    private javax.swing.JLabel CasillaZ;
    private javax.swing.JTextArea Cola1SF;
    private javax.swing.JTextArea Cola1Z;
    private javax.swing.JTextArea Cola2SF;
    private javax.swing.JTextArea Cola2Z;
    private javax.swing.JTextArea Cola3SF;
    private javax.swing.JTextArea Cola3Z;
    private javax.swing.JTextArea ColaRSF;
    private javax.swing.JTextArea ColaRZ;
    private javax.swing.JTextField CountSF;
    private javax.swing.JTextField CountZ;
    private javax.swing.JScrollPane Scroll1SF;
    private javax.swing.JScrollPane Scroll1Z;
    private javax.swing.JScrollPane Scroll2SF;
    private javax.swing.JScrollPane Scroll2Z;
    private javax.swing.JScrollPane Scroll3SF;
    private javax.swing.JScrollPane Scroll3Z3;
    private javax.swing.JScrollPane ScrollRSF;
    private javax.swing.JScrollPane ScrollRZ;
    private javax.swing.JTextField StatusSF;
    private javax.swing.JTextField StatusZ;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
